apiVersion: v1
kind: ConfigMap
metadata:
  name: bugtest-config
data:
  application.yaml: |
    micronaut:
      application:
        name: bugtest

  logback.xml: |
    <configuration>

      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <withJansi>true</withJansi>
        <!-- encoders are assigned the type
            ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
        <encoder>
            <pattern>%cyan(%d{HH:mm:ss.SSS}) %gray([%thread]) %highlight(%-5level) %green( [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}] )  %magenta(%logger{36}) - %msg%n</pattern>
        </encoder>
      </appender>

      <root level="info">
          <appender-ref ref="STDOUT" />
      </root>
    </configuration>